remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-default-layout
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

collections:
  items:
    permalink: "/questions/:path"
    output: true
    order:
      - questions/detectitem.md
      - questions/customitemtag.md
      - questions/amountitems.md

callouts:
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: yellow
  caution:
    title: Caution
    color: red
